### ISSUE TITLE
Top 2 Nav icons are covered by the pageTitle on the Dashboard page

### ISSUE THREAD

**Issue by triccs** [triccs/membrane-frontend#2]
I've messed with the z-index but can't get it to bring the Nav icons to the front. This is annoying but if you're on the dashboard there are at least other options to navigate with.

**Comment by LittleLionMan** [comment]
in global.css:

.sticky {
  height: 100%;
  position: fixed;
  bottom: 0%;
  z-index: 2;
  opacity: 0.8
}

**Comment by triccs** [comment]
Fixed: https://github.com/triccs/membrane-frontend/commit/04fc55b4ae6b31ef77bc9bf07c6b5827e592ae58
