### ISSUE TITLE
Basic Stats on the Dashboard

### ISSUE THREAD

**Issue by triccs** [triccs/membrane-frontend#8]
Best case they are animated and count up on load. Ex: https://yama.finance/

**Comment by LittleLionMan** [comment]
Can you add the queries for the data you want on the component to Dashboard.tsx?
If we need this data in other components, too, we shouldn't do it in the component, but use something like a redux-store or maybe zustand (?) to save it as a state. I believe it will be advantegeous to set up a store soon to handle states between components with ease. It will get chaotic using props I believe.
